# Generated by Django 6.0.7 on 2026-07-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(default='0 Hours', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.FloatField(default=4.5),
        ),
    ]
