# Generated by Django 6.0.7 on 2026-07-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_quiz_quizresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
